# Generated by Django 4.2.2 on 2023-06-21 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firm',
            name='image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='firms'),
        ),
    ]
